name: Deploy to Firebase

on:
  workflow_dispatch:
  push:
    branches:
      - firebase-prod
      - firebase-dev

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: (npm install && cd functions && npm install && npm run build)

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # Deploy to production environment
      - name: Set environment variables for firebase-prod and deploy
        if: github.ref == 'refs/heads/firebase-prod'
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PROD }}
          PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID_PROD }}
          FUNCTIONS_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID_PROD }}
          FUNCTIONS_REGION: ${{ secrets.FIREBASE_REGION_PROD }}
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions --project ${PROJECT_ID}

      # Deploy to development environment
      - name: Set environment variables for firebase-dev and deploy
        if: github.ref == 'refs/heads/firebase-dev'
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_DEV }}
          PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID_DEV }}
          FUNCTIONS_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID_DEV }}
          FUNCTIONS_REGION: ${{ secrets.FIREBASE_REGION_DEV }}
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions --project ${PROJECT_ID}
