name: Deploy to Firebase

on:
  workflow_dispatch:
  push:
    branches:
      - firebase-prod
      - firebase-dev

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: (npm install && cd functions && npm install)

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Set environment variables for firebase-prod
        if: github.ref == 'refs/heads/firebase-prod'
        run:
          echo "PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID_PROD }}" >> $GITHUB_ENV |
          echo "FUNCTIONS_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID_PROD }}" >> $GITHUB_ENV |
          echo "FUNCTIONS_REGION=${{ env.FIREBASE_REGION_PROD }}" >> $GITHUB_ENV

      - name: Set environment variables for firebase-dev
        if: github.ref == 'refs/heads/firebase-dev'
        run:
          echo "PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID_DEV }}" >> $GITHUB_ENV |
          echo "FUNCTIONS_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID_DEV }}" >> $GITHUB_ENV |
          echo "FUNCTIONS_REGION=${{ env.FIREBASE_REGION_DEV }}" >> $GITHUB_ENV

      - name: Deploy to Firebase (production)
        if: github.ref == 'refs/heads/firebase-prod'
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PROD }}
          FUNCTIONS_REGION: ${{ env.FIREBASE_REGION }}"
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions --project ${PROJECT_ID}

      - name: Deploy to Firebase (development)
        if: github.ref == 'refs/heads/firebase-dev'
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_DEV }}
          FUNCTIONS_REGION: ${{ env.FIREBASE_REGION }}"
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions --project ${PROJECT_ID}
