name: Deploy to Firebase

on:
  workflow_dispatch:
  push:
    branches:
      - firebase-prod
      - firebase-dev

jobs:
  deploy:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: (cd functions && npm install)

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Set environment variables for firebase-prod
        if: github.ref == 'refs/heads/firebase-prod'
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PROD }}
        run: echo "Set environment variables for firebase-prod"

      - name: Set environment variables for firebase-dev
        if: github.ref == 'refs/heads/firebase-dev'
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_DEV }}
        run: echo "Set environment variables for firebase-dev"

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions,storage,firestore
